// Dados pré-definidos baseados no schema do banco
import type {
  FuncionarioCompleto,
  Departamento,
  Cargo,
  JornadaTrabalho,
  MarcacaoDePonto,
  SolicitacaoDeFerias,
  Licencas,
  Dispositivo,
  CentroDeCusto,
} from "./types"

// Jornadas de Trabalho
export const mockJornadas: JornadaTrabalho[] = [
  {
    idJornadaTrabalho: 1,
    turno: "Comercial",
    hora_inicio: "08:00",
    hora_fim: "17:00",
    duracao_intervalo: 60,
    tolerancia_atraso: 10,
    tolerancia_saida: 10,
    permitir_extra: true,
    limite_extra: 120,
  },
  {
    idJornadaTrabalho: 2,
    turno: "Flexível",
    hora_inicio: "09:00",
    hora_fim: "18:00",
    duracao_intervalo: 60,
    tolerancia_atraso: 15,
    tolerancia_saida: 15,
    permitir_extra: true,
    limite_extra: 100,
  },
  {
    idJornadaTrabalho: 3,
    turno: "Meio Período",
    hora_inicio: "08:00",
    hora_fim: "12:00",
    duracao_intervalo: 0,
    tolerancia_atraso: 5,
    tolerancia_saida: 5,
    permitir_extra: false,
    limite_extra: 0,
  },
]

// Departamentos
export const mockDepartamentos: Departamento[] = [
  {
    idDepartamento: "TI001",
    nome: "Tecnologia da Informação",
    sigla: "TI",
    descricao: "Departamento responsável pela infraestrutura tecnológica",
    gerente: "admin",
    localizacao: "Prédio A - 3º Andar",
  },
  {
    idDepartamento: "RH001",
    nome: "Recursos Humanos",
    sigla: "RH",
    descricao: "Gestão de pessoas e processos administrativos",
    gerente: "gerente",
    localizacao: "Prédio A - 2º Andar",
  },
  {
    idDepartamento: "VD001",
    nome: "Vendas",
    sigla: "VD",
    descricao: "Equipe comercial e relacionamento com clientes",
    gerente: "gerente",
    localizacao: "Prédio B - 1º Andar",
  },
  {
    idDepartamento: "MK001",
    nome: "Marketing",
    sigla: "MK",
    descricao: "Marketing digital e comunicação",
    gerente: "funcionario",
    localizacao: "Prédio B - 2º Andar",
  },
  {
    idDepartamento: "FN001",
    nome: "Financeiro",
    sigla: "FN",
    descricao: "Controladoria e gestão financeira",
    gerente: "admin",
    localizacao: "Prédio A - 1º Andar",
  },
]

// Cargos
export const mockCargos: Cargo[] = [
  {
    idCargo: 1,
    nome: "Desenvolvedor Full Stack",
    nivel: "Sênior",
    salario_base: 12000.0,
    descricao: "Desenvolvimento de aplicações web completas",
    ativo: true,
    departamento: "TI001",
    jornada_trabalho: 1,
  },
  {
    idCargo: 2,
    nome: "Analista de RH",
    nivel: "Pleno",
    salario_base: 8500.0,
    descricao: "Gestão de processos de recursos humanos",
    ativo: true,
    departamento: "RH001",
    jornada_trabalho: 1,
  },
  {
    idCargo: 3,
    nome: "Vendedor",
    nivel: "Pleno",
    salario_base: 6000.0,
    descricao: "Vendas e relacionamento com clientes",
    ativo: true,
    departamento: "VD001",
    jornada_trabalho: 1,
  },
  {
    idCargo: 4,
    nome: "Analista de Marketing",
    nivel: "Júnior",
    salario_base: 5500.0,
    descricao: "Campanhas de marketing digital",
    ativo: true,
    departamento: "MK001",
    jornada_trabalho: 2,
  },
  {
    idCargo: 5,
    nome: "Estagiário TI",
    nivel: "Estagiário",
    salario_base: 1500.0,
    descricao: "Suporte técnico e desenvolvimento",
    ativo: true,
    departamento: "TI001",
    jornada_trabalho: 3,
  },
  {
    idCargo: 6,
    nome: "Contador",
    nivel: "Sênior",
    salario_base: 10000.0,
    descricao: "Contabilidade e controladoria",
    ativo: true,
    departamento: "FN001",
    jornada_trabalho: 1,
  },
]

// Funcionários Completos
export const mockFuncionarios: FuncionarioCompleto[] = [
  {
    matricula: "admin",
    foto_funcionario: "/placeholder.svg?height=100&width=100",
    rank: "5",
    senha: "123456",
    pessoa: {
      idPessoa: 1,
      endereco: "01310100",
      titulo_eleitor: "123456789012",
      carteira_identidade: "ID001",
      numero_celular: "(11) 99999-0001",
      email_pessoal: "admin@email.com",
      carteira_trabalho: "12345678901",
    },
    carteira_identidade: {
      id: "ID001",
      cpf: "11111111111",
      rg: "123456789",
      nome_completo: "Administrador do Sistema",
      nome_da_mae: "Maria Administradora",
      nome_do_pai: "João Administrador",
      sexo: "Masculino",
      data_nascimento: new Date("1985-05-15"),
      raca_cor: "Branco",
      estado_civil: "Casado",
      orgao_expedidor: "SSP-SP",
      data_expedicao: "2020-01-15",
    },
    endereco: {
      cep: "01310100",
      numero: "1000",
      logradouro: "Avenida Paulista",
      cidade: "São Paulo",
      complemento: "Conjunto 101",
      bairro: "Bela Vista",
      uf: "SP",
    },
    banco: {
      idBanco: 1,
      banco: "Banco do Brasil",
      tipo_conta: "Corrente",
      agencia: "1234-5",
      conta: "12345-6",
      chave_pix: "admin@empresa.com",
      funcionario: "admin",
    },
    contrato: {
      idContratoTrabalho: 1,
      data_admissao: new Date("2020-01-15"),
      tipo_contrato: "CLT",
      status: "Ativo",
      salario_contratual: 15000.0,
      funcionario: "admin",
      departamento: "TI001",
      jornada_trabalho: 1,
      cargo: 1,
    },
    cargo_info: mockCargos[0],
    departamento_info: mockDepartamentos[0],
  },
  {
    matricula: "gerente",
    foto_funcionario: "/placeholder.svg?height=100&width=100",
    rank: "4",
    senha: "123456",
    pessoa: {
      idPessoa: 2,
      endereco: "04038001",
      titulo_eleitor: "123456789013",
      carteira_identidade: "ID002",
      numero_celular: "(11) 99999-0002",
      email_pessoal: "gerente@email.com",
      carteira_trabalho: "12345678902",
    },
    carteira_identidade: {
      id: "ID002",
      cpf: "22222222222",
      rg: "987654321",
      nome_completo: "Maria Silva Santos",
      nome_da_mae: "Ana Silva",
      nome_do_pai: "Carlos Santos",
      sexo: "Feminino",
      data_nascimento: new Date("1988-08-20"),
      raca_cor: "Branco",
      estado_civil: "Solteiro",
      orgao_expedidor: "SSP-SP",
      data_expedicao: "2021-03-10",
    },
    endereco: {
      cep: "04038001",
      numero: "500",
      logradouro: "Rua Vergueiro",
      cidade: "São Paulo",
      complemento: "Apto 45",
      bairro: "Vila Mariana",
      uf: "SP",
    },
    banco: {
      idBanco: 2,
      banco: "Itaú",
      tipo_conta: "Corrente",
      agencia: "5678-9",
      conta: "54321-0",
      chave_pix: "22222222222",
      funcionario: "gerente",
    },
    contrato: {
      idContratoTrabalho: 2,
      data_admissao: new Date("2021-03-10"),
      tipo_contrato: "CLT",
      status: "Ativo",
      salario_contratual: 10000.0,
      funcionario: "gerente",
      departamento: "RH001",
      jornada_trabalho: 1,
      cargo: 2,
    },
    cargo_info: mockCargos[1],
    departamento_info: mockDepartamentos[1],
  },
  {
    matricula: "funcionario",
    foto_funcionario: "/placeholder.svg?height=100&width=100",
    rank: "2",
    senha: "123456",
    pessoa: {
      idPessoa: 3,
      endereco: "05407002",
      titulo_eleitor: "123456789014",
      carteira_identidade: "ID003",
      numero_celular: "(11) 99999-0003",
      email_pessoal: "funcionario@email.com",
      carteira_trabalho: "12345678903",
    },
    carteira_identidade: {
      id: "ID003",
      cpf: "33333333333",
      rg: "456789123",
      nome_completo: "João Pedro Costa",
      nome_da_mae: "Fernanda Costa",
      nome_do_pai: "Roberto Costa",
      sexo: "Masculino",
      data_nascimento: new Date("1992-12-05"),
      raca_cor: "Preto",
      estado_civil: "Casado",
      orgao_expedidor: "SSP-SP",
      data_expedicao: "2022-06-15",
    },
    endereco: {
      cep: "05407002",
      numero: "200",
      logradouro: "Rua Cardeal Arcoverde",
      cidade: "São Paulo",
      complemento: "Casa 2",
      bairro: "Pinheiros",
      uf: "SP",
    },
    banco: {
      idBanco: 3,
      banco: "Caixa Econômica Federal",
      tipo_conta: "Poupança",
      agencia: "9876-5",
      conta: "98765-4",
      chave_pix: "(11) 99999-0003",
      funcionario: "funcionario",
    },
    contrato: {
      idContratoTrabalho: 3,
      data_admissao: new Date("2022-06-15"),
      tipo_contrato: "CLT",
      status: "Ativo",
      salario_contratual: 7500.0,
      funcionario: "funcionario",
      departamento: "VD001",
      jornada_trabalho: 1,
      cargo: 3,
    },
    cargo_info: mockCargos[2],
    departamento_info: mockDepartamentos[2],
  },
  {
    matricula: "operador",
    foto_funcionario: "/placeholder.svg?height=100&width=100",
    rank: "1",
    senha: "123456",
    pessoa: {
      idPessoa: 4,
      endereco: "01310100",
      titulo_eleitor: "123456789015",
      carteira_identidade: "ID004",
      numero_celular: "(11) 99999-0004",
      email_pessoal: "operador@email.com",
      carteira_trabalho: "12345678904",
    },
    carteira_identidade: {
      id: "ID004",
      cpf: "44444444444",
      rg: "789123456",
      nome_completo: "Ana Beatriz Lima",
      nome_da_mae: "Beatriz Lima",
      nome_do_pai: "Carlos Lima",
      sexo: "Feminino",
      data_nascimento: new Date("1995-03-22"),
      raca_cor: "Amarelo",
      estado_civil: "Solteiro",
      orgao_expedidor: "SSP-SP",
      data_expedicao: "2023-01-10",
    },
    endereco: {
      cep: "01310100",
      numero: "800",
      logradouro: "Avenida Paulista",
      cidade: "São Paulo",
      complemento: "Sala 205",
      bairro: "Bela Vista",
      uf: "SP",
    },
    banco: {
      idBanco: 4,
      banco: "Santander",
      tipo_conta: "Corrente",
      agencia: "1111-1",
      conta: "11111-1",
      chave_pix: "ana.lima@email.com",
      funcionario: "operador",
    },
    contrato: {
      idContratoTrabalho: 4,
      data_admissao: new Date("2023-01-10"),
      tipo_contrato: "Estágio",
      status: "Ativo",
      salario_contratual: 1800.0,
      funcionario: "operador",
      departamento: "TI001",
      jornada_trabalho: 3,
      cargo: 5,
    },
    cargo_info: mockCargos[4],
    departamento_info: mockDepartamentos[0],
  },
]

// Dispositivos de Ponto
export const mockDispositivos: Dispositivo[] = [
  {
    idDispositivo: "REP001",
    modelo: "Biométrico Pro 3000",
    localizacao: "Entrada Principal",
    online: true,
  },
  {
    idDispositivo: "REP002",
    modelo: "Facial Recognition X1",
    localizacao: "Prédio A - 2º Andar",
    online: true,
  },
  {
    idDispositivo: "REP003",
    modelo: "Cartão RFID Basic",
    localizacao: "Prédio B - 1º Andar",
    online: false,
  },
]

// Marcações de Ponto
export const mockMarcacoes: MarcacaoDePonto[] = [
  {
    idMarcacaoDePonto: "MP001",
    funcionario: "admin",
    dispositivo: "REP001",
    data_hora: new Date("2024-01-06T08:00:00"),
    tipo_marcacao: "Entrada",
    status: "Válida",
    metodo_autenticacao: "biometria",
    assinatura_digital: "SHA256:abc123...",
    data_registro: new Date("2024-01-06T08:00:05"),
  },
  {
    idMarcacaoDePonto: "MP002",
    funcionario: "admin",
    dispositivo: "REP001",
    data_hora: new Date("2024-01-06T12:00:00"),
    tipo_marcacao: "Intervalo",
    status: "Válida",
    metodo_autenticacao: "biometria",
    assinatura_digital: "SHA256:def456...",
    data_registro: new Date("2024-01-06T12:00:02"),
  },
  {
    idMarcacaoDePonto: "MP003",
    funcionario: "gerente",
    dispositivo: "REP002",
    data_hora: new Date("2024-01-06T08:15:00"),
    tipo_marcacao: "Entrada",
    status: "Válida",
    metodo_autenticacao: "facial",
    assinatura_digital: "SHA256:ghi789...",
    data_registro: new Date("2024-01-06T08:15:03"),
  },
]

// Solicitações de Férias
export const mockFerias: SolicitacaoDeFerias[] = [
  {
    idSolicitacaoDeFerias: 1,
    aprovador_por: "admin",
    funcionario: "funcionario",
    data_inicio_solicitacao: new Date("2024-02-01"),
    data_fim_solicitacao: new Date("2024-02-15"),
    dias: 15,
    data_aprovacao: new Date("2024-01-10"),
    status: "Aprovado",
    resposta: "Férias aprovadas. Bom descanso!",
  },
  {
    idSolicitacaoDeFerias: 2,
    aprovador_por: "gerente",
    funcionario: "operador",
    data_inicio_solicitacao: new Date("2024-03-10"),
    data_fim_solicitacao: new Date("2024-03-20"),
    dias: 10,
    status: "Pendente",
    resposta: null,
  },
]

// Licenças
export const mockLicencas: Licencas[] = [
  {
    idLicenca: 1,
    funcionario: "gerente",
    data_inicio: new Date("2024-01-05"),
    data_fim: new Date("2024-01-15"),
    motivo: "Licença médica - cirurgia",
    anexo: "atestado_medico_001.pdf",
    status: "Ativa",
  },
  {
    idLicenca: 2,
    funcionario: "funcionario",
    data_inicio: new Date("2024-02-20"),
    data_fim: new Date("2024-06-20"),
    motivo: "Licença paternidade",
    anexo: "certidao_nascimento.pdf",
    status: "Pendente de Documento",
  },
]

// Centros de Custo
export const mockCentrosCusto: CentroDeCusto[] = [
  {
    idCentroDeCusto: "CC001001",
    nome: "Desenvolvimento de Software",
    descricao: "Custos relacionados ao desenvolvimento",
    data_criacao: new Date("2020-01-01"),
    conta_contabil: "6.1.1.001",
    departamento: "TI001",
  },
  {
    idCentroDeCusto: "CC002001",
    nome: "Recrutamento e Seleção",
    descricao: "Custos com processos de RH",
    data_criacao: new Date("2020-01-01"),
    conta_contabil: "6.1.2.001",
    departamento: "RH001",
  },
  {
    idCentroDeCusto: "CC003001",
    nome: "Comissões de Vendas",
    descricao: "Comissões e bonificações",
    data_criacao: new Date("2020-01-01"),
    conta_contabil: "6.1.3.001",
    departamento: "VD001",
  },
]
